In [115]:
with open("the-verdict.txt", 'r',encoding="utf-8") as f:
    raw_data=f.read()
print(raw_data[:99])
print(len(raw_data))

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 
20479


In [27]:
import regex as re
preprocess=re.split(r'([,.:;?_!"()\']|\s|--)',raw_data)

In [29]:
print(preprocess[:100])

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius', '--', 'though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough', '--', 'so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ']


In [36]:
preprocessed=[item.strip() for item in preprocess if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [50]:
new=sorted(set(preprocessed))
print(new[:30])

['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed']


In [56]:
vocab={token:integer for integer,token in enumerate(new)}

In [62]:
for i,item in enumerate(vocab.items()):
    if i<50:
        print(item)

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)


In [146]:
class simple_tokenizer:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s,i in vocab.items()}
    def encoder(self,text):
        preprocessed=re.split(r'([,.:;?_!"()\']|\s|--)',text)
        preprocessed=[item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decoder(self,ids):
        result=" ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1',result)
        return text

In [148]:
text="""The height of his glory"--that was what the women called it."""
tokenizer=simple_tokenizer(vocab)

In [150]:
text = """It's the last he painted, you know,"""
        
ids = tokenizer.encoder(text)
print(ids)

[56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5]


In [152]:
print(tokenizer.decoder(ids))

It' s the last he painted, you know,


In [160]:
all_tokens=sorted(set(new))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
vocab={token:integer for integer,token in enumerate(all_tokens)}

In [162]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
class simple_tokenizer:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s,i in vocab.items())
    def encoder(self,text):
         preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
         preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        preprocessed=[item if item in 

In [1]:
!pip install tiktoken

   ---------------------------------------- 0.0/893.9 kB ? eta -:--:--
   ---------------------------------------- 10.2/893.9 kB ? eta -:--:--
   - ------------------------------------- 30.7/893.9 kB 325.1 kB/s eta 0:00:03
   ---- ---------------------------------- 92.2/893.9 kB 751.6 kB/s eta 0:00:02
   ----- -------------------------------- 122.9/893.9 kB 722.1 kB/s eta 0:00:02
   ------- ------------------------------ 174.1/893.9 kB 871.5 kB/s eta 0:00:01
   -------- ----------------------------- 194.6/893.9 kB 841.6 kB/s eta 0:00:01
   --------- ---------------------------- 225.3/893.9 kB 724.0 kB/s eta 0:00:01
   ---------- --------------------------- 256.0/893.9 kB 749.3 kB/s eta 0:00:01
   ------------ ------------------------- 286.7/893.9 kB 737.3 kB/s eta 0:00:01
   ---------------- --------------------- 389.1/893.9 kB 897.8 kB/s eta 0:00:01
   ------------------- ------------------ 450.6/893.9 kB 909.8 kB/s eta 0:00:01
   ----------------------- ---------------- 532.5/893.9 k

In [ ]:
"""Byte pair Encoding """

In [21]:
import tiktoken
import importlib
print(importlib.metadata.version("tiktoken"))

0.9.0


In [23]:
text="Hello world !!!!!"
tokenizer = tiktoken.get_encoding("gpt2")

In [24]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})


In [27]:
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [29]:
decoder=tokenizer.decode(integers)

In [31]:
print(decoder)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [33]:
text=("dfgdfg dfg kk sy")
integer= tokenizer.encode(text,allowed_special={"<|endoftext|>"})
print(integers)
decoder=tokenizer.decode(integer)
print(decoder)


[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]
dfgdfg dfg kk sy


In [17]:
import tiktoken
encoder={"gpt2":tiktoken.get_encoding("gpt2"),"gpt3":tiktoken.get_encoding("p50k_base")}
vocab_size={model:encoding.n_vocab for model,encoding in encoder.items()}
for model,vocab in vocab_size.items():
    print(f'{model}-->{vocab}')

gpt2-->50257
gpt3-->50281


In [ ]:
#24-03-2025 today i have learnt about torch , n_vocab which is build method to find the sizze of vocabulary

In [ ]:
e

In [35]:
"""
===========================================
             CREATE INPUT TARGET PAIRS
===========================================
"""


'\n===========================================\n             CREATE INPUT TARGET PAIRS\n===========================================\n'

In [37]:
with open("the-verdict.txt",'r',encoding="utf-8") as f:
    raw_text=f.read()
encoder=tokenizer.encode(raw_text)
print(encoder[:50])

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11]


In [39]:
len(encoder)

5145

In [41]:
sample=encoder[:50]

In [43]:
#creating context_size
context_size =4
x=sample[:4]
y=sample[1:context_size+1]
print(f"x: {x}")
print(f"y:     {y}")

x: [40, 367, 2885, 1464]
y:     [367, 2885, 1464, 1807]


In [45]:
for i in range(1,context_size+1):
    context=sample[:i] 
    desired=sample[i]
    print(context, "--->" ,desired)

[40] ---> 367
[40, 367] ---> 2885
[40, 367, 2885] ---> 1464
[40, 367, 2885, 1464] ---> 1807


In [47]:
for i in range(1,context_size+1):
    context=sample[:i]
    desired=sample[i]
    print(tokenizer.decode(context), "--->" ,tokenizer.decode([desired]))

I --->  H
I H ---> AD
I HAD --->  always
I HAD always --->  thought


In [49]:
from torch.utils.data import Dataset, DataLoader
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [51]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [53]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [55]:
import torch
import tiktoken
print("PyTorch version:", torch.__version__)
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version: 2.6.0+cpu
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [57]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [59]:
#Creating embedding layers

In [1]:
# for example let us consider we have a sentense that contain 6 word, each word is token

In [3]:
#sentence-->"quick fox is in the house"  and the vocabulary id of the sentence is [4,0,3,2,5,1]

In [5]:
# and now we are trying to create a embedding layers it is also called as look up table ,and is is 2d array (vector dim,vocab)

In [93]:
import torch
inputs= torch.tensor([2, 3, 5, 1])

In [95]:
out_dim=3
vocab_size=6
embedding=torch.nn.Embedding(vocab_size,out_dim) # it will create a embedding layers and the table will contain 6 rows,3 cols

In [107]:
print(embedding.weight.shape) 
emb=embedding(inputs)
print(emb.shape)#weights will return the weight which are assigned randomly

torch.Size([6, 3])
torch.Size([4, 3])


In [17]:
# we can get each vocab id values

In [99]:
print(embedding.weight[3])
# the output of this is the fourth row in the matrics, and these embedding weights are further optimised ass the part of LLM traing

tensor([-0.3705,  0.9944, -0.4975], grad_fn=<SelectBackward0>)


In [101]:
#postional embedding 

In [103]:
# this is last step in the preprocessing the data to fed in to llm ,intially we assign random value to the tokens 

In [105]:
# there are 2 types of postional embeddings actual and relational,actual is used when there is fixed size sequence
#finalembedding values=positional embedding+input embedding value,which can store the postion information also

In [109]:
vocab= 50256
out_dim=256
embedding_layers=torch.nn.Embedding(vocab,out_dim)

In [157]:
print(embedding_layers.weight)
print(embedding_layers.weight.shape)

Parameter containing:
tensor([[-0.6050,  0.1398, -0.0721,  ..., -0.6158,  0.3069,  0.8245],
        [-1.5410, -0.9663, -1.8412,  ...,  0.5697, -1.0209, -0.3935],
        [ 1.2595, -0.0836, -1.3133,  ..., -0.9393, -1.9312,  0.7490],
        ...,
        [-0.3781,  0.0614,  2.3069,  ..., -0.4582, -0.0806, -0.6688],
        [ 0.4665, -0.7378, -0.5742,  ..., -1.1120, -1.1221, -0.9053],
        [ 0.3817, -0.5956, -0.8147,  ..., -1.1816, -1.3363,  1.9665]],
       requires_grad=True)
torch.Size([50256, 256])


In [129]:
max_len=4
dataloder=create_dataloader_v1(raw_data, batch_size=8, max_length=max_len, 
                         stride=max_len)
data =iter(dataloder)
inputs,target=next(data)
print(inputs)

tensor([[   11,  6405,   257,  5527],
        [ 3436,    11,   290,  1645],
        [  262,  6473,   438,  5562],
        [  938,   475,   530,   553],
        [  588,   683,   438,  8807],
        [   11, 12704,   257,  1310],
        [ 2215,   262,   530,  1517],
        [ 1359,   290,   965,  1397]])


In [131]:
print(target)

tensor([[ 6405,   257,  5527, 27075],
        [   11,   290,  1645,  1752],
        [ 6473,   438,  5562,   314],
        [  475,   530,   553,   673],
        [  683,   438,  8807,   314],
        [12704,   257,  1310,  2952],
        [  262,   530,  1517,   326],
        [  290,   965,  1397,    11]])


In [133]:
embeddings=embedding_layers(inputs)

In [137]:
print(embeddings.shape)

torch.Size([8, 4, 256])


In [147]:

positional_embedding=torch.nn.Embedding(max_len,out_dim)
print(positional_embedding.weight.shape)

torch.Size([4, 256])


In [173]:
pos_embeddings_layer = positional_embedding(torch.arange(max_len))
print(pos_embeddings_layer[1])
print(pos_embeddings_layer[2])

tensor([-1.8220e+00,  8.6425e-01, -1.8508e-01, -1.0823e+00,  1.6627e-01,
        -4.1529e-01,  1.0453e+00, -9.0473e-02,  4.6338e-01, -1.9372e-01,
        -1.4759e+00, -9.6808e-01,  1.0758e+00, -1.0225e+00,  7.6635e-01,
        -1.7472e+00, -9.7972e-01,  4.2885e-01,  2.6151e+00,  2.2810e-01,
         1.3635e+00, -6.5099e-02,  2.8649e-01,  3.1370e-01, -4.0296e-01,
         9.7504e-02, -4.3693e-01, -9.4205e-01, -7.0550e-01,  7.6422e-02,
         1.2984e+00,  1.4404e-02,  7.3587e-01, -1.1252e+00,  6.6131e-01,
        -1.9933e-01, -3.0482e-01, -1.3131e+00,  4.6865e-01, -1.4626e-01,
         1.1872e-01,  3.8299e-01, -7.6120e-01, -1.6018e+00,  2.0062e-01,
        -9.0893e-02, -9.8629e-02, -4.0145e-01, -8.0305e-01, -1.0757e+00,
         1.2520e+00,  5.6389e-01, -1.3878e-01,  1.9541e+00,  1.5287e+00,
        -8.5846e-01, -1.0039e+00,  1.9675e+00, -1.1889e+00,  3.5575e-01,
        -2.1741e+00, -8.2599e-01,  9.2608e-01, -4.1156e-01,  4.5936e-01,
         3.1565e-01, -1.4682e-01, -3.0241e-01, -5.7

### final_embeddings=embeddings+pos_embeddings_layer

In [161]:
print(final_embeddings)

tensor([[[ 1.9988, -0.5149,  0.7897,  ..., -0.2232,  1.3689, -0.4255],
         [-2.0955,  1.0882, -0.1274,  ..., -0.3236,  1.4284,  0.8635],
         [-0.1366,  0.7911, -1.0750,  ...,  4.5298, -0.5612, -1.4319],
         [ 0.1610,  3.2377, -1.9857,  ..., -0.1351,  1.1687,  0.0733]],

        [[ 0.4882, -1.2724,  0.3640,  ...,  0.3591,  1.6726, -0.5937],
         [-1.1446,  0.5286,  0.4174,  ...,  1.3894,  1.5488,  0.5062],
         [-1.5095,  0.7531, -0.8817,  ...,  1.3828, -0.9507, -1.3376],
         [-1.4237,  1.4147, -4.2738,  ...,  1.0002,  0.7777,  2.2051]],

        [[ 1.7267,  2.3527, -0.3981,  ..., -0.7703,  2.0535, -0.4336],
         [-2.1615,  1.5871, -0.7354,  ..., -0.2248,  1.9919,  1.6214],
         [ 0.9534,  1.6284, -2.1856,  ...,  2.9086, -0.2398, -2.3083],
         [-0.3370,  0.3713, -3.9851,  ..., -1.9749,  2.5017,  0.4478]],

        ...,

        [[ 1.9988, -0.5149,  0.7897,  ..., -0.2232,  1.3689, -0.4255],
         [-1.8379, -1.5482, -1.5281,  ...,  0.2909,  2.47